<a href="https://colab.research.google.com/github/Mas-Azi/Desain-dan-Analisis-Algoritma/blob/main/Pertemuan_3_DAA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
alist = ["Syafa", 19,"Dugong", True]
print("alist = ", alist)


alist =  ['Syafa', 19, 'Dugong', True]


Latihan 1

In [ ]:
Mahasiswa = ["Muhammad azi saputra", "2021071032","Informatika", "DAA","14/9/2022","Universitas Pembangunan Jaya"]
print("Mahasiswa = ", Mahasiswa)

Mahasiswa =  ['Muhammad azi saputra', '2021071032', 'Informatika', 'DAA', '14/9/2022', 'Universitas Pembangunan Jaya']


In [ ]:
bin_color = ['Red', 'Green', 'Blue', 'yellow']
bin_color[1]

'Green'

In [ ]:
Nim = Mahasiswa[1]
print("NIM = ", Nim)

NIM =  2021071032


In [ ]:
Kampus = Mahasiswa[5]
print("Kampus = ", Kampus)

Kampus =  Universitas Pembangunan Jaya


In [ ]:
#Mengambil lebih dari satu list menggunakan array
bin_color = ['Red', 'Green', 'Blue', 'Yellow']
bin_color[0:3]

['Red', 'Green', 'Blue']

In [ ]:
Mahasiswa[1:3]

[2021071032, 'Informatika']

In [ ]:
bin_color = ['Red', 'Green', 'Blue', 'Yellow']
for aColor in bin_color:
  print(aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [ ]:
for cetak in Mahasiswa:
  print("UPJ", cetak)

UPJ Muhammad azi saputra
UPJ 2021071032
UPJ Informatika
UPJ DAA
UPJ 14/9/2022
UPJ Universitas Pembangunan Jaya


struktur data Tuples

In [ ]:
bin_colors = ('White', 'Biru Sky', 'Ungu pastel', 'Pink')
print(bin_colors[1])
print(bin_colors[:2])
print(bin_colors[2:])

Biru Sky
('White', 'Biru Sky')
('Ungu pastel', 'Pink')


In [ ]:
Upj = ('Universitas', 'Pembangunan', 'Jaya')
print(Upj)
Upj[:1]

('Universitas', 'Pembangunan', 'Jaya')


('Universitas',)

In [ ]:
Neasted_tuple = ((100), (200,(400, 500),600), (300), (400, 800))
print("Pertama", Neasted_tuple[0])
print("Kedua", Neasted_tuple[1][2])
print("Ketiga", Neasted_tuple[2])
print("Keempat", Neasted_tuple[3])

Pertama 100
Kedua 600
Ketiga 300
Keempat (400, 800)


In [ ]:
bin_colors ={"manual_color": "Yellow", "approved_color": "Green", "refused_color":"red"}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'red'}


In [ ]:
bin_colors.get('approved_color')
#Memanggil data approved_color
print(bin_colors['approved_color'])

Green


In [ ]:
bin_colors['approved_color']="Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'red'}


In [ ]:
data ={"Nama":"Muhammad Azi Saputra", 
       "NIM":"2021071032", 
       "Prodi":"Informatika", 
       "Universitas":"UPJ"
}
print(data)

{'Nama': 'Muhammad Azi Saputra', 'NIM': '2021071032', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [ ]:
green = {'Grass', 'Leaves'}
print(green)

{'leaves', 'Grass'}


In [ ]:
yellow = {'dandelions', 'leaves', 'fire hyrdrant'}
red = {'fire hydrant', 'blood', 'rose', 'leaves'}
print(yellow|red)
print(yellow&red)

{'leaves', 'fire hyrdrant', 'rose', 'dandelions', 'fire hydrant', 'blood'}
{'leaves'}


import pandas

In [ ]:
import pandas as pd

In [ ]:

df = pd.DataFrame([['1', 'Fares', 32, True],
                  ['2', 'Elena', 23, False],
                  ['3', 'Steven', 29, True]
])
print(df)


   0       1   2      3
0  1   Fares  32   True
1  2   Elena  23  False
2  3  Steven  29   True


In [ ]:
df.columns = ['id', 'Name', 'age', 'decision']
print(df)

  id    Name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   29      True


In [ ]:
#seleksi kolom
df[['Name', 'age']]

Name  age
0   Fares   32
1   Elena   23
2  Steven   29

In [ ]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [ ]:
df.iloc[1:3,:]

id    Name  age  decision
1  2   Elena   23     False
2  3  Steven   29      True

In [ ]:
df[df.age>30]

id   Name  age  decision
0  1  Fares   32      True

In [ ]:
df[(df.age<35)&(df.decision==True)]

id    Name  age  decision
0  1   Fares   32      True
2  3  Steven   29      True

tabel 

In [ ]:
df = pd.DataFrame([['1', 'Informatika', 50, 30, 20], 
                   ['2', 'Sistem Informasi', 55, 30, 25], 
                   ['3', 'Teknik Sipil', 40, 30, 10]])

In [ ]:
df.columns = ['no', 'Prodi', 'Mahasiswa', 'Lakilaki', 'Perempuan']
df

no             Prodi  Mahasiswa  Lakilaki  Perempuan
0  1       Informatika         50        30         20
1  2  Sistem Informasi         55        30         25
2  3      Teknik Sipil         40        30         10

Matrik

In [ ]:
import numpy as np

In [ ]:
myMatrix = np.array([
                    [11, 12, 13], 
                    [21, 22, 23],
                    [31, 32, 33]])
print (myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
print (type(myMatrix))

<class 'numpy.ndarray'>


In [ ]:
myMatrix2 = np.array([
    [100, 200, 300],
    [700, 600, 500],
    [900, 1000, 800],
])
print (f'Original Array:\n{myMatrix2}')
myMatrix2_transposed = myMatrix2.transpose()
print (f'Transposed Array:\n{myMatrix2_transposed}')

Original Array:
[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
Transposed Array:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


Vektro

In [ ]:
myVector = [22, 33, 44, 55]
print (myVector)
print (type(myVector))

[22, 33, 44, 55]
<class 'list'>


In [ ]:
myVector = np.array ([22, 33, 44, 55])
print (myVector)
print (type(myVector))

[22 33 44 55]
<class 'numpy.ndarray'>


Stack

In [ ]:
class Stack:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def push(self, item):
    self.items.append(item)
  def pop(self):
    return self.items.pop()
  def peek(self):
    return self.items[len(self.items)-I]
  def size(self):
    return len(self.items)

In [ ]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push("Blue")
stack.push("Yellow")

print(stack.pop())

print(stack.isEmpty())

Yellow
False


queue

In [ ]:
class Queue(object):
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def enqueue(self, item):
    self.items.insert(0,item)
  def dequeue(self):
    return self.items.pop()
  def size(self):
    return len(self.items)

In [ ]:

queue=Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')
print(queue.size())

4


In [ ]:
print(queue.dequeue())
print(queue.dequeue())

Red
Green
